MVC增删改查+分页/MVC增删改查+分页/DD.EF/Controllers/InfoController.cs
using HPIT.Data.Core;
using HPIT.Survey.Portal.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DD.dal;
namespace DD.EF.Controllers
{
    public class InfoController : Controller
    {
        // GET: Info
        public ActionResult Index()
        {
            return View();
        }

        //[HttpPost]
        public DeluxeJsonResult QueryPageData(SearchModel<DD.dal.Login_Info> search)
        {
            int total = 0;
            var result = dal.fenye.Instance.GetPageData(search, out total);
            var totalPages = total % search.PageSize == 0 ? total / search.PageSize : total / search.PageSize + 1;
            return new DeluxeJsonResult(new{Data = result,Total = total,TotalPages = totalPages}, "yyyy-MM-dd HH: mm");
        }
    }
}

MVC增删改查+分页/MVC增删改查+分页/DD.EF/Controllers/USERController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DD.dal;
namespace DD.EF.Controllers
{
    public class USERController : Controller
    {
        // GET: USER
        public ActionResult Index()
        {
            List<Login_Info> loing = User_dal.getlist();
            return View(loing);
        }
        /// <summary>
        /// 添加 
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            //两种不同类型list的转换 new SelectListItem()是实例化一个新对象
            ViewBag.Rolename = User_dal.Roleslist().Select(r => new SelectListItem()
            { Text = r.Rolename, Value = r.Roleid.ToString() }
            ).ToList();
            return View();
        }
        public ActionResult CreateModel(Login_Info model) {
            if (User_dal.AddUser(model)>0) {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Create");
            }
        }
        /// <summary>
        /// 传值
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Update(int id) {
            Login_Info match = User_dal.details(id);
            //下拉框设置
            ViewBag.Rolename = User_dal.Roleslist().Select(r => new SelectListItem()
            { Text = r.Rolename, Value = r.Roleid.ToString() }
            ).ToList();
            return View(match);
        }

        public ActionResult Details(int id)
        {
            Login_Info match = User_dal.details(id);
            //下拉框设置
            //ViewBag.Rolename = User_dal.Roleslist().Select(r => new SelectListItem()
            //{ Text = r.Rolename, Value = r.Roleid.ToString() }
            //).ToList();
            return View(match);
        }
        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult UpdateModel(Login_Info model) {
            if (User_dal.Update(model)>0) {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Update");
            }
        }
        /// <summary>
        /// 删除方法一无dal层 无外表连接
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        //public ActionResult Delete(int id) {
        //    user_model model = new user_model();
        //    var user = model.Login_Info.Where(p => p.UserId == id);
        //    model.Login_Info.Remove(user.ToList()[0]);
        //    model.SaveChanges();
        //    return View("Index", model.Login_Info.ToList());
        //}

        public ActionResult Delete(int id) {
            User_dal.deleteinfo(id);
            return RedirectToAction("Index");
        }
    }
}

MVC增删改查+分页/MVC增删改查+分页/DD.EF/Views/USER/Create.cshtml
@model DD.dal.Login_Info

@{
    Layout = "~/Views/USER/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link href="~/JS/paging.css" rel="stylesheet" />
    <link href="~/JS/bootstrap.css" rel="stylesheet" />
</head>
<body>
    @using (Html.BeginForm("CreateModel", "USER"))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Login_Info</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserPwd, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserPwd, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserPwd, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Usersex, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Usersex, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Usersex, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Usertime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Usertime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Usertime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Useraddress, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Useraddress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Useraddress, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Roleid, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @* 下拉框设置 这里用到了封箱和拆箱的知识 *@
                    @Html.DropDownList("Roleid",(ViewBag.Rolename as IEnumerable<SelectListItem>))
                    @*@Html.EditorFor(model => model.Roleid, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Roleid, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

MVC增删改查+分页/MVC增删改查+分页/DD.EF/Views/USER/Details.cshtml
@model DD.dal.Login_Info

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Login_Info</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserPwd)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserPwd)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Usersex)
            </dt>

            <dd>
                @(Model.Usersex == 0 ? "男" : "女")
                @*@Html.DisplayFor(model => model.Usersex)*@
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Usertime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Usertime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Useraddress)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Useraddress)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserEmail)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserEmail)
            </dd>

            <dt>

                @Html.DisplayNameFor(model => model.Rolename)
            </dt>

            <dd>
 
                @Html.DisplayFor(model => model.Rolename)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.UserId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

MVC增删改查+分页/MVC增删改查+分页/DD.EF/Views/USER/Index.cshtml
@model IEnumerable<DD.dal.Login_Info>

@{
    //引用模板页 引用外部JS等文件
    Layout = "~/Views/USER/_Layout.cshtml";

}
@section styles{
    <style>
        h2 {
            color: aqua;
        }
    </style>
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
   <link href="~/JS/bootstrap.css" rel="stylesheet" />
    <link href="~/JS/paging.css" rel="stylesheet" />
</head>
<body>

    <h2>全表查询</h2>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserPwd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usersex)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usertime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Useraddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Roleid)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserPwd)
                </td>
                <td>
                    @(item.Usersex == 0 ? "男" : "女")
                    @*@Html.DisplayFor(modelItem => item.Usersex)*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Usertime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Useraddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserEmail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rolename)

                </td>
                <td>
                    @Html.ActionLink("编辑", "Update", new { id = item.UserId }) |
                    @Html.ActionLink("详情", "Details", new { id = item.UserId }) |
                    @Html.ActionLink("删除", "Delete", new { id = item.UserId })
                    @Html.ActionLink("添加", "Create", new { id = item.UserId })
                </td>
            </tr>
        }

    </table>
    @section script{
        @*<script>
            $(function () {
                alert("要飞");
            })
        </script>*@
    }
</body>

</html>

MVC增删改查+分页/MVC增删改查+分页/DD.EF/Views/USER/Update.cshtml
@model DD.dal.Login_Info

@{
    Layout = "~/Views/USER/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update</title>
    <link href="~/JS/paging.css" rel="stylesheet" />
    <link href="~/JS/bootstrap.css" rel="stylesheet" />
</head>
<body>
    @using (Html.BeginForm("UpdateModel","USER"))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Login_Info</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.UserId)
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserPwd, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserPwd, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserPwd, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Usersex, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                 
                    @Html.EditorFor(model => model.Usersex, new { htmlAttributes = new { @class = "form-control" } })
                   
                    @Html.ValidationMessageFor(model => model.Usersex, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Usertime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Usertime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Usertime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Useraddress, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Useraddress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Useraddress, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Roleid, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Roleid", (ViewBag.Rolename as IEnumerable<SelectListItem>))
                    @*@Html.EditorFor(model => model.Roleid, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Roleid, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

MVC增删改查+分页/MVC增删改查+分页/DD.EF/Views/USER/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/JS/jquery-3.3.1.js"></script>
    <script src="~/JS/jquery-3.3.1.min.js"></script>
    @*<script src="~/JS/JStext.js"></script>*@
    <script src="~/JS/paging.js"></script>
    @RenderSection("styles", false)

</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
@RenderSection("script", false)
</html>